name: ambient_light
description: "A powerful plugin to access ambient light sensor data on Android, iOS and macOS"
version: 0.1.3
homepage: https://github.com/ali-you
repository: https://github.com/ali-you/ambient-light-plugin
documentation: https://github.com/ali-you/ambient-light-plugin
issue_tracker: https://github.com/ali-you/ambient-light-plugin/issues
topics:
  - sensor
  - light
  - utils
  - ambient
  - brightness

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.aliyou.ambient_light
        pluginClass: AmbientLightPlugin
      ios:
        pluginClass: AmbientLightPlugin
      linux:
        pluginClass: AmbientLightPlugin
      macos:
        pluginClass: AmbientLightPlugin
      windows:
        pluginClass: AmbientLightPluginCApi